// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: mist-cloud-comm/mist.proto

package moteconnection

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [START messages]
type MistMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gateway     uint64               `protobuf:"fixed64,1,opt,name=gateway,proto3" json:"gateway,omitempty"`         // EUI64 of the gateway that the message is travelling through
	Destination uint64               `protobuf:"fixed64,2,opt,name=destination,proto3" json:"destination,omitempty"` // EUI64 of the destination
	Source      uint64               `protobuf:"fixed64,3,opt,name=source,proto3" json:"source,omitempty"`           // EUI64 of the source
	Payload     []byte               `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`           // Message payload
	Amid        uint32               `protobuf:"varint,5,opt,name=amid,proto3" json:"amid,omitempty"`                // uint16 - extended Active Message ID
	Rssi        int32                `protobuf:"varint,6,opt,name=rssi,proto3" json:"rssi,omitempty"`                // int8 - message RSSI (dB), -128 when not available
	Lqi         uint32               `protobuf:"varint,7,opt,name=lqi,proto3" json:"lqi,omitempty"`                  // uint8 - message LQI (0-255), 0 when not available
	Group       uint32               `protobuf:"varint,8,opt,name=group,proto3" json:"group,omitempty"`              // uint16 - extended Active Message Group or PAN ID
	Channel     uint32               `protobuf:"varint,9,opt,name=channel,proto3" json:"channel,omitempty"`          // uint8 - radio channel
	Timestamp   *timestamp.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`      // Timestamp of the message as it entered the Mist daemon
}

func (x *MistMessage) Reset() {
	*x = MistMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mist_cloud_comm_mist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MistMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MistMessage) ProtoMessage() {}

func (x *MistMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mist_cloud_comm_mist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MistMessage.ProtoReflect.Descriptor instead.
func (*MistMessage) Descriptor() ([]byte, []int) {
	return file_mist_cloud_comm_mist_proto_rawDescGZIP(), []int{0}
}

func (x *MistMessage) GetGateway() uint64 {
	if x != nil {
		return x.Gateway
	}
	return 0
}

func (x *MistMessage) GetDestination() uint64 {
	if x != nil {
		return x.Destination
	}
	return 0
}

func (x *MistMessage) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *MistMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MistMessage) GetAmid() uint32 {
	if x != nil {
		return x.Amid
	}
	return 0
}

func (x *MistMessage) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *MistMessage) GetLqi() uint32 {
	if x != nil {
		return x.Lqi
	}
	return 0
}

func (x *MistMessage) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *MistMessage) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *MistMessage) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_mist_cloud_comm_mist_proto protoreflect.FileDescriptor

var file_mist_cloud_comm_mist_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x69, 0x73, 0x74, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x63, 0x6f, 0x6d,
	0x6d, 0x2f, 0x6d, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x69,
	0x73, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x0b, 0x4d, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x06, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x6d, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x61, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x73, 0x73, 0x69, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x73, 0x73, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x71, 0x69,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6c, 0x71, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x38, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x24, 0x5a, 0x22, 0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x74, 0x68, 0x69, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2f,
	0x6d, 0x69, 0x73, 0x74, 0x2d, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mist_cloud_comm_mist_proto_rawDescOnce sync.Once
	file_mist_cloud_comm_mist_proto_rawDescData = file_mist_cloud_comm_mist_proto_rawDesc
)

func file_mist_cloud_comm_mist_proto_rawDescGZIP() []byte {
	file_mist_cloud_comm_mist_proto_rawDescOnce.Do(func() {
		file_mist_cloud_comm_mist_proto_rawDescData = protoimpl.X.CompressGZIP(file_mist_cloud_comm_mist_proto_rawDescData)
	})
	return file_mist_cloud_comm_mist_proto_rawDescData
}

var file_mist_cloud_comm_mist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mist_cloud_comm_mist_proto_goTypes = []interface{}{
	(*MistMessage)(nil),         // 0: mist.MistMessage
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_mist_cloud_comm_mist_proto_depIdxs = []int32{
	1, // 0: mist.MistMessage.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mist_cloud_comm_mist_proto_init() }
func file_mist_cloud_comm_mist_proto_init() {
	if File_mist_cloud_comm_mist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mist_cloud_comm_mist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MistMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mist_cloud_comm_mist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mist_cloud_comm_mist_proto_goTypes,
		DependencyIndexes: file_mist_cloud_comm_mist_proto_depIdxs,
		MessageInfos:      file_mist_cloud_comm_mist_proto_msgTypes,
	}.Build()
	File_mist_cloud_comm_mist_proto = out.File
	file_mist_cloud_comm_mist_proto_rawDesc = nil
	file_mist_cloud_comm_mist_proto_goTypes = nil
	file_mist_cloud_comm_mist_proto_depIdxs = nil
}
